### PR TITLE
docs: Fix Warnings and Notes

### LINKED ISSUE #917: Warning messages broken in docs
I noticed some warning messages seem to be broken in the documentation, for example in the [Usage section](https://immediate-mode-ui.github.io/Nuklear/index.html#autotoc_md5):

Image

I thought this might be a simple PR but I'm afraid I'm new to Nuklear and Doxygen! I've included my attempted fixes below but neither seem ideal.

```diff
diff --git a/src/HEADER.md b/src/HEADER.md
index 60b2478..f01ac6b 100644
--- a/src/HEADER.md
+++ b/src/HEADER.md
@@ -88,9 +88,20 @@ Also optionally define the symbols listed in the section "OPTIONAL DEFINES"
 below in header and implementation mode if you want to use additional functionality
 or need more control over the library.
 
+<!-- Current broken warning -->
 !!! WARNING
     Every time nuklear is included define the same compiler flags. This very important not doing so could lead to compiler errors or even worse stack corruptions.
 
+<!-- Doxygen warning - matches other header warnings but invalid markdown and adds unwanted '!!!' above -->
+!!! \warning
+    Every time nuklear is included define the same compiler flags. This very important not doing so could lead to compiler errors or even worse stack corruptions.
+
+<br >
+
+<!-- Github warning - valid markdown but doesn't match other header warnings -->
+> [!warning]
+> Every time nuklear is included define the same compiler flags. This very important not doing so could lead to compiler errors or even worse stack corruptions.
+
 ### Flags
 Flag                            | Description
 --------------------------------|------------------------------------------
```

Image

### PR DESCRIPTION
**Pull request by RobLoach**
Fixes #917

### CODE REVIEW

**Comment by rswinkle** [comment]
Looks good.

File: src/nuklear.h [hunk 1]
```diff
@@ -1409,8 +1405,7 @@ NK_API struct nk_window *nk_window_find(const struct nk_context *ctx, const char
  * # # nk_window_get_bounds
  * \returns a rectangle with screen position and size of the currently processed window
  *
- * !!! \warning
- *     Only call this function between calls `nk_begin_xxx` and `nk_end`
+ * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
  * ```c
  * struct nk_rect nk_window_get_bounds(const struct nk_context *ctx);
  * ```
```
Comment (sleeptightAnsiC) [inline src/nuklear.h:1412]: Places, like this one, where the warning is immediately followed by the snippet, are not displaying correctly, because the snippet is being "swallowed" by the warning box. See:

Image

If you just add one newline right after the warning, it will fix the issue, like so:

Image

**Review by sleeptightAnsiC — CHANGES_REQUESTED** [review]
Could you please fix all occurrences of the issue I just mentioned?

You can use the diff from below. I already tried it locally. Hopefully, I haven't missed anything else.

<details><summary>diff</summary>
<p>

```diff
diff --git a/nuklear.h b/nuklear.h
index 2b7aa57..92e9849 100644
--- a/nuklear.h
+++ b/nuklear.h
@@ -1622,6 +1622,7 @@ NK_API struct nk_window *nk_window_find(const struct nk_context *ctx, const char
  * \returns a rectangle with screen position and size of the currently processed window
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * struct nk_rect nk_window_get_bounds(const struct nk_context *ctx);
  * ```
@@ -1640,6 +1641,7 @@ NK_API struct nk_rect nk_window_get_bounds(const struct nk_context *ctx);
  * \returns the position of the currently processed window.
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * struct nk_vec2 nk_window_get_position(const struct nk_context *ctx);
  * ```
@@ -1658,6 +1660,7 @@ NK_API struct nk_vec2 nk_window_get_position(const struct nk_context *ctx);
  * \returns the size with width and height of the currently processed window.
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * struct nk_vec2 nk_window_get_size(const struct nk_context *ctx);
  * ```
@@ -1676,6 +1679,7 @@ NK_API struct nk_vec2 nk_window_get_size(const struct nk_context *ctx);
  * \returns the width of the currently processed window.
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * float nk_window_get_width(const struct nk_context *ctx);
  * ```
@@ -1693,6 +1697,7 @@ NK_API float nk_window_get_width(const struct nk_context *ctx);
  * \returns the height of the currently processed window.
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * float nk_window_get_height(const struct nk_context *ctx);
  * ```
@@ -1712,6 +1717,7 @@ NK_API float nk_window_get_height(const struct nk_context* ctx);
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
  * \warning Do not keep the returned panel pointer around, it is only valid until `nk_end`
+ *
  * ```c
  * struct nk_panel* nk_window_get_panel(struct nk_context *ctx);
  * ```
@@ -1849,6 +1855,7 @@ NK_API void nk_window_get_scroll(const struct nk_context *ctx, nk_uint *offset_x
  * # # nk_window_has_focus
  * \returns if the currently processed window is currently active
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * nk_bool nk_window_has_focus(const struct nk_context *ctx);
  * ```
@@ -1866,6 +1873,7 @@ NK_API nk_bool nk_window_has_focus(const struct nk_context *ctx);
  * # # nk_window_is_hovered
  * Return if the current window is being hovered
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * nk_bool nk_window_is_hovered(struct nk_context *ctx);
  * ```
diff --git a/src/nuklear.h b/src/nuklear.h
index 2f431e6..9ec94d4 100644
--- a/src/nuklear.h
+++ b/src/nuklear.h
@@ -1406,6 +1406,7 @@ NK_API struct nk_window *nk_window_find(const struct nk_context *ctx, const char
  * \returns a rectangle with screen position and size of the currently processed window
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * struct nk_rect nk_window_get_bounds(const struct nk_context *ctx);
  * ```
@@ -1424,6 +1425,7 @@ NK_API struct nk_rect nk_window_get_bounds(const struct nk_context *ctx);
  * \returns the position of the currently processed window.
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * struct nk_vec2 nk_window_get_position(const struct nk_context *ctx);
  * ```
@@ -1442,6 +1444,7 @@ NK_API struct nk_vec2 nk_window_get_position(const struct nk_context *ctx);
  * \returns the size with width and height of the currently processed window.
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * struct nk_vec2 nk_window_get_size(const struct nk_context *ctx);
  * ```
@@ -1460,6 +1463,7 @@ NK_API struct nk_vec2 nk_window_get_size(const struct nk_context *ctx);
  * \returns the width of the currently processed window.
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * float nk_window_get_width(const struct nk_context *ctx);
  * ```
@@ -1477,6 +1481,7 @@ NK_API float nk_window_get_width(const struct nk_context *ctx);
  * \returns the height of the currently processed window.
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * float nk_window_get_height(const struct nk_context *ctx);
  * ```
@@ -1496,6 +1501,7 @@ NK_API float nk_window_get_height(const struct nk_context* ctx);
  *
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
  * \warning Do not keep the returned panel pointer around, it is only valid until `nk_end`
+ *
  * ```c
  * struct nk_panel* nk_window_get_panel(struct nk_context *ctx);
  * ```
@@ -1633,6 +1639,7 @@ NK_API void nk_window_get_scroll(const struct nk_context *ctx, nk_uint *offset_x
  * # # nk_window_has_focus
  * \returns if the currently processed window is currently active
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * nk_bool nk_window_has_focus(const struct nk_context *ctx);
  * ```
@@ -1650,6 +1657,7 @@ NK_API nk_bool nk_window_has_focus(const struct nk_context *ctx);
  * # # nk_window_is_hovered
  * Return if the current window is being hovered
  * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
+ *
  * ```c
  * nk_bool nk_window_is_hovered(struct nk_context *ctx);
  * ```
```

</p>
</details>

File: src/nuklear.h [hunk 2]
```diff
@@ -1409,8 +1405,7 @@ NK_API struct nk_window *nk_window_find(const struct nk_context *ctx, const char
  * # # nk_window_get_bounds
  * \returns a rectangle with screen position and size of the currently processed window
  *
- * !!! \warning
- *     Only call this function between calls `nk_begin_xxx` and `nk_end`
+ * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`
```
Comment (RobLoach) [inline src/nuklear.h]:
``` suggestion
 * \warning Only call this function between calls `nk_begin_xxx` and `nk_end`.
 *
```

**Review by sleeptightAnsiC — APPROVED** [review]
Thanks.
